// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0F8Sx1yfNDs_voIVI6dfQrHNSz5NiQPI',
    authDomain: 'maids-3fe29.firebaseapp.com',
    projectId: 'maids-3fe29',
    storageBucket: 'maids-3fe29.appspot.com',
    messagingSenderId: '276643601744',
    appId: '1:276643601744:web:d5d0ff65c439d390d66055'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKKjWMrlyjJRNxY8484MMxeBpaHLYvkM',
    appId: '1:276643601744:android:1b0f7465a9e86bbed66055',
    messagingSenderId: '276643601744',
    projectId: 'maids-3fe29',
    storageBucket: 'maids-3fe29.appspot.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-_jXdfBfqlOvMBGyI--tFcmHCCErvMA',
    iosBundleId: 'maids.cocis.com',
    appId: '1:276643601744:ios:c609cfcc73918d01d66055',
    storageBucket: 'maids-3fe29.appspot.com',
    messagingSenderId: '276643601744',
    iosClientId: '276643601744-m4ei55alrkpcss1t1trdpp5ai4ojn1lj.apps.googleusercontent.com',
    projectId: 'maids-3fe29'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyrX3xwE_RqkEZ8d_PJhUGqVmgrrGBVXc',
    appId: '1:431535707736:ios:6128174d1b07cb7d77dc2d',
    messagingSenderId: '431535707736',
    projectId: 'maidmatch-4c8e2',
    storageBucket: 'maidmatch-4c8e2.appspot.com',
    iosClientId: '431535707736-hmqhc0jht892fgmr9qho0pldcehac3qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.maidmatchApp',
  );
}
